name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra
        sudo apt-get install -y texlive-fonts-recommended texlive-science biber

    - name: Build
      run: make

    - name: Export PDF
      uses: actions/upload-artifact@v3
      with:
        name: summary.pdf
        path: summary/summary.pdf
